---
- name: postgresql should listen on all ports
  become_user: postgres
  lineinfile: dest=/etc/postgresql/9.3/main/postgresql.conf
              regexp="^listen_addresses"
              line="listen_addresses = '*'" state=present

- name: postgresql should allow access to host
  become_user: postgres
  copy:
    dest: /etc/postgresql/9.3/main/pg_hba.conf
    content: |
      local   all   postgres   trust
      local   all   all        peer
      host    all   all        0.0.0.0/0   md5
  notify: restart postgresql

- name: terminate the connection to the db
  become_user: postgres
  command: psql -c "select pg_terminate_backend(pid) from pg_stat_activity where datname = 'rails_dev';"

- name: drop development database if exist
  become_user: postgres
  command: psql -c "DROP DATABASE IF EXISTS rails_dev;"

- name: delete root database if exist
  become_user: postgres
  command: psql -c "DROP DATABASE IF EXISTS root;"

- name: delete root user if exist
  become_user: postgres
  command: psql -c "DROP ROLE IF EXISTS root;"
  
- name: create root user
  become_user: postgres
  command: psql -c "CREATE ROLE root SUPERUSER CREATEDB LOGIN;"

- name: create root database
  become_user: postgres
  command: psql -c "CREATE DATABASE root"
  
- name: create development database
  command: psql -c "CREATE DATABASE rails_dev"