---
- name: Upgrade all packages to the latest version
  apt: update_cache=yes

- name: Install essential packages
  apt: pkg={{ item }} state=present force=yes
  with_items:
    - git-core
    - git
    - curl
    - wget
    - zlib1g-dev
    - libssl-dev
    - libreadline-dev
    - libyaml-dev
    - libxml2-dev
    - libxslt1-dev
    - libcurl4-openssl-dev
    - python-software-properties
    - libffi-dev
    - automake
    - bison
    - pkg-config
    - autoconf
    - libreadline6
    - postgresql
    - postgresql-contrib
    - libpq-dev
    - python-dev
    - python-psycopg2
    - imagemagick
    - zsh

- name: Fetch oh-my-zsh
  git: repo=git://github.com/robbyrussell/oh-my-zsh.git
       dest=~/.oh-my-zsh

- name: Clone .zshrc for oh-my-zsh
  copy: src=~/.oh-my-zsh/templates/zshrc.zsh-template
        dest=~/.zshrc

- name: Change current user shell
  user:
    name: root
    shell: /bin/zsh
