---
- name: Upgrade all packages to the latest version
  apt: update_cache=yes

- name: Install essential packages
  apt: pkg={{ item }} state=present force=yes
  with_items:
    - git-core
    - curl
    - zlib1g-dev
    - build-essential
    - libssl-dev
    - libreadline-dev
    - libyaml-dev
    - libsqlite3-dev
    - sqlite3
    - libxml2-dev
    - libxslt1-dev
    - libcurl4-openssl-dev
    - python-software-properties
    - libffi-dev
    - automake
    - bison
    - pkg-config
    - autoconf
    - libreadline6
    - postgresql
    - postgresql-contrib
    - libpq-dev
    - python-dev
    - python-psycopg2
    - imagemagick
